### ISSUE TITLE
Adding Ray1Map

### ISSUE THREAD

**Issue by RayCarrot** [Helias/Crash-Bandicoot-Resources#3]
I wanted to suggest adding [Ray1Map](https://github.com/Adsolution/Ray1Map) to the list here. It's a map viewer project I've worked on where I last year reverse engineered the Vicarious Visions Crash GBA games (so all except Crash of the Titans) and added them to the map viewer (they can be viewed in the web version here: https://raym.app/maps_r1). Downloading the local Unity project also has some extra tools for extracting animations, cutscenes, text, object scripts etc. The actual code for the data formats can right now be found [here in the repo](https://github.com/Adsolution/Ray1Map/tree/master/Assets/Scripts/Games/GBAVV/Serializable).

**Comment by Helias** [comment]
Hey! I strongly like raym.app I used it for Rayman M / Arena, just to check it a bit.
I was aware of this tool but I never connected it with Crash Bandicoot.

It's a wonderful job, congrats! I am adding it istantly.
