### ISSUE TITLE
About Crash Bash support in ctr-tools

### ISSUE THREAD

**Issue by DCxDemo** [Helias/Crash-Bandicoot-Resources#4]
there is some invalid info about crash bash and ctr-tools - it's able to extract all files from multiple crash bash versions and partially gives them human readable names, that's what partially refers to.

cheers

**Comment by Helias** [comment]
oh, I am sorry, thanks for reporting it!
I also saw that you created an issue in the CrashBashEx, thanks, I think that I will join the discord channel only to follow a bit some progress
